### ISSUE TITLE
Round price in two decimal digits to send to the API

### ISSUE THREAD

**Issue by ChristianAF** [woocommerce/woocommerce-gateway-amazon-pay#131]
**Describe the bug**
WooCommerce support more that 2 digit on their setting, this enables merchants to connect with some ERP systems that required this due to rounding issues. We need to round the values to be sent to the API so we avoid the error response:
```
 "InvalidParameterValue": [
            "The value '0.9000' provided for 'chargeAmount.Amount' is invalid."
        ]
```
Reference  report: https://wordpress.org/support/topic/prices-4-digits-and-no-payment-possible/

**To Reproduce**
1. Set WooCommerce to work with more than 2 decimal digits
2. try to perform a purchase (will be on error)
3. Check the error log

**Expected behavior**
Amazon pay should be able to handle payments on store that use more that 2 decimal digits on their prices.

**Isolating the problem (mark completed items with an [x]):**
- [ x ] I have deactivated other plugins and confirmed this bug occurs when only the extension is active.
- [ x ] I can reproduce this bug consistently using the steps above.

**Comment by dpanta94** [comment]
Closing this is fixed by [pull#150](https://github.com/woocommerce/woocommerce-gateway-amazon-pay/pull/150)
