### ISSUE TITLE
Amazon Pay as only active payment method shows confusing checkout error.

### ISSUE THREAD

**Issue by ryanr14** [woocommerce/woocommerce-gateway-amazon-pay#142]
**Describe the bug**
If you have Amazon pay as the only payment method on the site, you see the button near the top of checkout.

But you'll also see the message that says "Sorry, it seems that there are no available payment methods for your state. Please contact us if you require assistance or wish to make alternate arrangements."

**To Reproduce**
1. Make Amazon Pay you're only active payment method.
2. Go to checkout
3. See error

**Screenshots**
![Markup on 2022-01-11 at 23:15:30](https://user-images.githubusercontent.com/867748/149062891-0a440325-6a24-45e0-8dac-1a6608ece2e1.png)

**Expected behavior**
Amazon pay is available, why you saying it ain't now?! This message shouldn't be shown if someone chooses to use Amazon Pay only.

**Comment by alexiglesias31** [comment]
Closing this issue as there has been no recent news. Feel free to reopen if there are further updates or discussions.
