### ISSUE TITLE
Redefinition of parameter $quotaMax

### ISSUE THREAD

**Issue by dwainm** [woocommerce/woocommerce-gateway-amazon-pay#15]
#### Affected ticket(s)

Slack: C07414X4N/p1554222452092300

#### What I expected

No critical errors

#### What happened instead

`2019-04-02T15:34:32+00:00 CRITICAL Redefinition of parameter $quotaMax in /app/public/wp-content/plugins/pay-with-amazon-express-checkout/MarketplaceWebServiceSellers/Model/ResponseHeaderMetaData.php on line 31`

#### Steps to reproduce the issue

> It may have been triggered during setup, but I cannot tell. Regardless, I was going to search for it before creating an issue to ensure that it wasn’t something expected.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by lauramelos** [comment]
This error comes from a different plugin called: pay-with-amazon-express-checkout.
