### ISSUE TITLE
Can't update subscription payment method if user is already logged in to Amazon 

### ISSUE THREAD

**Issue by dwainm** [woocommerce/woocommerce-gateway-amazon-pay#17]
#### Affected ticket(s)
1970133-zen

#### What I expected
To update payment method on a subscription, as described here:

https://docs.woocommerce.com/document/subscriptions/customers-view/#section-12

#### What happened instead
The process works fine if I'm switching from a different payment method to Amazon, or if the customer is logged out from Amazon and needs to sign in again. The problem only happens if I'm already logged in to Amazon in Woo:

![Screenshot](https://cld.wthms.co/CI1Uk2+)
Screenshot: https://cld.wthms.co/CI1Uk2

In that case, I'm not able to complete the payment due to the following error:

```
Error encountered in OffAmazonPayments.Widgets.Consent : (InvalidBillingAgreementStatus) The BillingAgreementId C01-5296324-5202663 is in an invalid state
```

I'm not sure how long our integration keeps the user logged in to Amazon. I don't expect customers to update their subscription payment methods too often, so it shouldn't be a big problem if the user is only logged in for eg. 1 hour.

#### Steps to reproduce the issue
1. Enable Amazon Pay for subscriptions,
2. Add a subscription product to cart,
3. Checkout with Amazon and complete the order to activate the subscription,
4. Go to **My Account > My Subscriptions** and open subscription details,
5. Click **Change Payment** on the subscription page:

![Screenshot](https://cld.wthms.co/MIxrhh+)
Screenshot: https://cld.wthms.co/MIxrhh

6. Check the top of the page and see if the user is still logged in to Amazon:

![Screenshot](https://cld.wthms.co/CI1Uk2+)
Screenshot: https://cld.wthms.co/CI1Uk2

7. If it is, there will be an error in the Amazon iframe and browser console.

![Screenshot](https://cld.wthms.co/XkZqpl+)
Screenshot: https://cld.wthms.co/XkZqpl

8. Log out from Amazon using the link on the top of the page,
9. Repeat steps 4-6. User should be logged out this time:

![Screenshot](https://cld.wthms.co/MPIO4c+)
Screenshot: https://cld.wthms.co/MPIO4c

10. Login to Amazon again to complete the payment
11. Observe the billing details and checkbox loads correctly this time:

![Screenshot](https://cld.wthms.co/OVw9QN+)
Screenshot: https://cld.wthms.co/OVw9QN

12. Click the button and update.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by thenbrent** [comment]
Notes from `bianchif`:

> The issue is due to the rendering of the consent widget, which should not be shown on payment method update.

> The consent widget is needed only on subscription setup, but it should not be rendered again after the subscription is set up correctly. Rendering the wallet widget only is enough in this case.
