### ISSUE TITLE
Check if customer is already logged in with Amazon [code suggestion]

### ISSUE THREAD

**Issue by jrodger** [woocommerce/woocommerce-gateway-amazon-pay#23]
From a ticket:

> We noticed that some custom plugins we use have compatibility issues with the way the Amazon Pay extension hijacks the checkout page if the user is logged in via Amazon. For this, it would be awesome to have some official way to detect whether the user is logged in via Amazon or not. Is it possible to add something like the following snippet to the WC_Amazon_Payments_Advanced core class?
```
class WC_Amazon_Payments_Advanced { 
... 
public function is_user_logged_in() { 
return false === empty($this->reference_id) && empty($this->access_token); 
} 
}
```
I've chosen to label this as high because it may be an easy fix that would help with other compatibility issues.

Ticket: 1321439-zen

**Comment by alexiglesias31** [comment]
Closing this issue as there has been no recent news. Feel free to reopen if there are further updates or discussions.
