### ISSUE TITLE
Amazon Pay Button is displayed even when Out Of Stock

### ISSUE THREAD

**Issue by ChristianAF** [woocommerce/woocommerce-gateway-amazon-pay#251]
**Describe the bug**
https://wordpress.org/support/topic/button-is-displayed-even-when-out-of-stock/

Amazon Pay button is displayed on Product pages even when product is Out Of Stock. 
**To Reproduce**
1. on the Settings activate the option "Amazon Pay on product pages"
2. On Fron-end go to a product page that is out of stock
3. Button still displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/43881685/224689954-42782014-abce-4c49-8676-1f985f61a0ad.png)

**Expected behavior**
Button should not be displayed when product is out of stock
**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only the extension is active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by JakeDevLab** [comment]
Do we have any updates on this? Please advise.

**Comment by ChristianAF** [comment]
We also need to check the "Backorder" status of products. @dpanta94
