### ISSUE TITLE
After migration V1 keys to V2, the Amazon pay meta box doesn't show the Admin button for Authorize or Capture

### ISSUE THREAD

**Issue by ChristianAF** [woocommerce/woocommerce-gateway-amazon-pay#254]
**Describe the bug**
https://www.loom.com/share/90f25d272bf443f29b2a0c9918e8ec5d

For reproduction: need to have transactions made with Amazon pay (Only Auth or Don't Authorize transactions) V1.

**Screenshots**
![image](https://user-images.githubusercontent.com/43881685/229599440-9735cf19-ad13-4921-987a-a28548a3de31.png)

**Expected behavior**
Amazon Metabox you have available the Interaction buttons after migrating keys to V2

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only the extension is active.
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by alexiglesias31** [comment]
Closing this issue as there has been no recent news. Feel free to reopen if there are further updates or discussions.
