### ISSUE TITLE
Using Express checkout on a Variable Virtual Subcription product page, is showing the Shipping address

### ISSUE THREAD

**Issue by ChristianAF** [woocommerce/woocommerce-gateway-amazon-pay#255]
**Describe the bug**
Should not show the Shipping address
![image](https://user-images.githubusercontent.com/43881685/229599992-bec61965-aee1-4016-a0c8-3a2c1b840b0b.png)

and after continuing, user needs to select payment again
![image](https://user-images.githubusercontent.com/43881685/229600026-507c470a-6d26-4a95-bb2e-c4a6f398a418.png)

**Expected behavior**
Should not show the Shipping address for virtual/downloadable products

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only the extension is active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by alexiglesias31** [comment]
This is fixed now, closing the ticket.
