### ISSUE TITLE
When the #billing_address_2 and #shipping_address_2 fields are hidden on the checkout form, they are undefined when using Amazon Pay

### ISSUE THREAD

**Issue by ChristianAF** [woocommerce/woocommerce-gateway-amazon-pay#258]
**Describe the bug**
When the #billing_address_2 and #shipping_address_2 fields are hidden on the checkout form, they are undefined when using Amazon Pay if the user has no info on those fields.

**Screenshots**
![image](https://user-images.githubusercontent.com/43881685/230382544-702602c9-940c-4c7f-a9b6-4342f307cc91.png)

**Expected behavior**
fields should be ignored if they don't have information.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only the extension is active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by ChristianAF** [comment]
Something related to WooCommerce v7.5 fixed on v7.6

**Comment by ChristianAF** [comment]
Some users still say that Woo version 7.6 did not fix the issue.

**Comment by ChristianAF** [comment]
https://github.com/woocommerce/woocommerce/issues/37736

**Comment by thisissandip** [comment]
Hey,

I tested with WooCommerce 7.6 and hid all checkout fields from **Appearances > Customize > WooCommerce > Checkout** and confirm this is reproducible.

![4cVcmF.png](https://user-images.githubusercontent.com/69596988/232883844-eba7de4e-5a2e-45b5-ac65-bfc57a4d6076.png)

This issue has been logged here: https://github.com/woocommerce/woocommerce/issues/37627#issuecomment-1515809125 and devs already have a fix which will be out in the next release

**Comment by ChristianAF** [comment]
Seems to be fixed
