### ISSUE TITLE
Center infotext vertically

### ISSUE THREAD

**Issue by ChristianAF** [woocommerce/woocommerce-gateway-amazon-pay#261]
**Describe the bug**
The message box on the the checkout page looks quite bad. I can’t change the button or (more important) the pretty useless text below the button, since it comes from Amazon. While the standard Woocommerce text is vertically centered, the AmazonPay infotext is not vertically aligned with the button.

reference: https://wordpress.org/support/topic/how-to-center-infotext-vertically/

**Comment by alexiglesias31** [comment]
Closing issue, support ticket already closed.
