### ISSUE TITLE
Add compatibility with plugin "CURCY – WooCommerce Multi Currency – Currency Switcher"

### ISSUE THREAD

**Issue by ChristianAF** [woocommerce/woocommerce-gateway-amazon-pay#272]
**Describe the bug**
the owner of the plugin wants to add his plugin to the compatibility list for multi-currency feature
https://villatheme.com/extensions/woo-multi-currency/

**Comment by Lavendervu** [comment]
Hi,

Thank you for your message. We'll continue monitoring the ticket and look forward to hearing from you. Have there been any updates regarding this compatibility request?

Best regards.

**Comment by Lavendervu** [comment]
Hi,

We would appreciate continuing our communication regarding the compatibility request. We aim to provide you with information that will assist you in considering compatibility.

We are aware that you have already made your plugin compatible with some currency plugins, and we kindly request that you consider adding our plugin to your compatibility list.

We are also providing you with our developer documentation for your reference. This documentation outlines the functions our plugin uses for price conversion. We hope this documentation proves helpful, and please do not hesitate to reach out if you require any further information or assistance.

Thank you for your attention and consideration.

Reference:

Our developer docs: [Here.
](https://docs.villatheme.com/woocommerce-multi-currency/#page_section_menu_6680)
[https://ibb.co/Zf40X44
https://ibb.co/KLK81nR](url)

**Comment by mrkapable007** [comment]
Hi,

I was wondering if this is now compatible?

**Comment by ChristianAF** [comment]
@mrkapable007 @Lavendervu with version 2.5.1 the plugin can be extendable to other multi-currency plugins. [Here is the link how to](https://github.com/woocommerce/woocommerce-gateway-amazon-pay/wiki/Adding-Compatibility-for-a-Multi%E2%80%90currency-Plugin-and-WooCommerce-Amazon-Pay-plugin)

**Comment by Lavendervu** [comment]
Thank you so much!
