### ISSUE TITLE
Rename options on "Login Authorization Mode" setting

### ISSUE THREAD

**Issue by jrodger** [woocommerce/woocommerce-gateway-amazon-pay#29]
The options on this setting are currently "Optimal" or "Popup"

![image](https://user-images.githubusercontent.com/686419/76987994-fa353780-693b-11ea-9319-b0faa78d667a.png)

These should be "Automatic" or "Popup".

**Comment by alexiglesias31** [comment]
Closing this issue as there has been no recent news. Feel free to reopen if there are further updates or discussions.
