### ISSUE TITLE
Customers cannot checkout when Amazon's state does not match WC predefinitions

### ISSUE THREAD

**Issue by dwainm** [woocommerce/woocommerce-gateway-amazon-pay#34]
**Bug description**
If the shipping address state set on Amazon does not match the values in the WC dropdown, customers are faced with an error regarding shipping selection and are not able to place the order.

This happens because the `shipping_state` that comes from Amazon does not match the ones predefined in WooCommerce for the country selected. In the screenshot below, the address uses *Lazio*, while Woo expects some other values. 

**To Reproduce**
1. Add a product to cart and Login with Amazon to checkout
2. Select an address that has a state not expected in WooCommerce (the one in the screenshot should work)
3. Try to place the order - it should fail with the message `No shipping method has been selected. Please double check your address, or contact us if you need any help`.

**Screenshots**
![image](https://user-images.githubusercontent.com/7714042/77453709-597cc700-6dd6-11ea-9b17-baee22047fd0.png)

**Expected behavior**
Users should be able to checkout, be prompted for missing fields (#35 ) or get instructions to correct their addresses on the Amazon dashboard.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only the extension is active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by dwainm** [comment]
How did this work when we were unsetting the shipping fields before #408? Seems like a user wouldn't even be able to select appropriate shipping if the checkout form didn't know which address it was being shipped to?

**Comment by dwainm** [comment]
> How did this work when we were unsetting the shipping fields before #408? Seems like a user wouldn't even be able to select appropriate shipping if the checkout form didn't know which address it was being shipped to?

This happens both pre and post #408, in fact, the screenshot was taken using `master` before merging it. It also happens when the Login app mode is disabled:

![image](https://user-images.githubusercontent.com/7714042/77537260-8a173c00-6e7c-11ea-8d92-b03ec585f8f0.png)


I'm not entirely aware of how shipping is calculated at checkout, but I think it has something to do with [`store_shipping_info_in_session`](https://github.com/woocommerce/woocommerce-gateway-amazon-payments-advanced/blob/master/includes/class-wc-gateway-amazon-payments-advanced.php#L586-L610). This makes sense for Login app clients, but I haven't looked deeply enough to figure out how it works when Login app is disabled.

**Comment by dwainm** [comment]
Hi Guys, 

Is this something that we could solve by prompting the dropdown for State selection from Woo in the page? 

The buyer would select the correct state field from the dropdown instead of using the one from the Amazon account in this case. For a "1 field mismatch" it's not a problem. 

Regards, 
Federico

**Comment by dwainm** [comment]
Yes, prompting the user for the State would be enough to solve this issue.

We have #423 to consolidate missing/mismatching data between Woo and Amazon, so fixing that issue would also fix this one.

**Comment by dwainm** [comment]
Thanks for the feedback, solving #423 sounds like it will cover more use cases.

In general I'm ok moving forward with an approach for which we would be asking the buyer to enter manually any information that is mandatory for the checkout but it's not provided in the Amazon address. Those information can be the province, the last name and eventually in limited cases the phone number usually.

**Comment by jessLundie** [comment]
Also reported in [forum here.](https://wordpress.org/support/topic/there-are-no-shipping-methods-available-27/)
