### ISSUE TITLE
 Checkout page sometimes not being found for merchantLoginRedirectURL value

### ISSUE THREAD

**Issue by vbelolapotkov** [woocommerce/woocommerce-gateway-amazon-pay#38]
Hello! I noticed that when creating a temporary wordpress instance with https://jurassic.ninja/create/, the merchantLoginRedirectURL is not populated correctly in the admin settings (where auto key exchange/merchant onboarding occurs). [The code](https://github.com/woocommerce/woocommerce-gateway-amazon-pay/blob/70abb654247a8b07d0b08f2f76580f5f18a622bf/woocommerce-gateway-amazon-payments-advanced.php#L854) should be adding **amazon_payments_advanced=true** to the end of the checkout URL, but it does not seem to be pulling in the checkout URL as it is just taking the current admin URL (without a base/fully qualified domain) and adding the parameter at the end:

`<input type="hidden" name="merchantLoginRedirectURLs[]" value="/wp-admin/admin.php?page=wc-settings&amp;tab=checkout&amp;section=amazon_payments_advanced&amp;amazon_payments_advanced=true">`

Why would the checkout page URL not be found, and is there a way to prevent this?

Thanks!

**Comment by dougaitken** [comment]
Similar - product pages have `?amazon_payments_advanced=true` in the page source even if the Amazon Pay option doesn't show. 

This forum post explains more - https://wordpress.org/support/topic/amazon_payments_advancedtrue-on-each-page/

This is resulting in the URL of the product being being reported in Google search and Google analytics as having that string:

page source (I've confirmed this on a test site):

https://www.dropbox.com/s/mfj0rima5phg5bi/Schermata%202020-10-02%20alle%2011.20.09.jpg

Google Search Console dashboard
https://www.dropbox.com/s/cc375vlrjqa340y/Schermata%202020-10-02%20alle%2011.24.06.jpg

**Comment by Polycarbonates** [comment]
I'm having the same issue ?amazon_payments_advanced=true. This is actually creating duplicate content and being indexed in the search engines. https://www.phsinc.com/equipment/cold-storage/nfs-1-freezer-spacer/?amazon_payments_advanced=true

**Comment by cl0udres** [comment]
This problem afflict our web site since months and months. Please fix it asap!
