### ISSUE TITLE
Missing order ID in session causes duplicate Amazon Pay requests

### ISSUE THREAD

**Issue by vbelolapotkov** [woocommerce/woocommerce-gateway-amazon-pay#43]
Bug raised by a user through live chat: 2855857-zen. First steps:

* Try and re-create the issue.
* The patch string came through stripped of whitespace so it won't apply. It'll be easy enough to do manually though.

**Describe the bug**
We have an issue with Amazon Payment for not logged customers, the problem is that because order id is not set the first time, the user has to repeat the process, and even if payment is captured only once, there are 2 order entries in the dasboard. Please find below the patch we used to workaround this problem, wp_parse_args already has amazon_reference_id index set as empty, so wp_parse_args will not update from get_post_meta, it is why we added a second check like so:

Fixed missing order ID in session causes duplicate Amazon Pay requests.

```
diff --git a/includes/class-wc-amazon-payments-advanced-api.php b/includes/class-wc-amazon-payments-advanced-api.php
index 3f0dfab12..49ebda038 100644
--- a/includes/class-wc-amazon-payments-advanced-api.php
+++ b/includes/class-wc-amazon-payments-advanced-api.php
@@ -756,11 +756,14 @@ class WC_Amazon_Payments_Advanced_API {
$args = wp_parse_args(
$args,
array(
- 'amazon_reference_id' => get_post_meta( $order_id, 'amazon_reference_id', true ),
'capture_now' => false,
)
);

+ if ( empty( $args['amazon_reference_id'] ) ) {
+ $args['amazon_reference_id'] = get_post_meta( $order_id, 'amazon_reference_id', true );
+ }
+
if ( ! $args['amazon_reference_id'] ) {
return new WP_Error( 'order_missing_reference_id', __( 'Order missing Amazon order reference ID.', 'woocommerce-gateway-amazon-payments-advanced' ) );
}
```

**Comment by DustinHartzler** [comment]
Also reported here: 19711676-hc
