### ISSUE TITLE
Define Acceptance Test / PR Test Prompts

### ISSUE THREAD

**Issue by dwainm** [woocommerce/woocommerce-gateway-amazon-pay#45]
Let's use this issue to collect things that we want to consider when making changes to this extension. We could use this for full fledged acceptance tests (e.g. for SAU/CAL work) and as a resource when writing tests for individual PRs. This could also be used potentially for defining automated e2e happy path tests.

Customers
- Test checkout with Japanese test customers with and without city entries ( #438 )

3D Secure
- Test checkout with cards requiring 3D Secure

**Comment by dwainm** [comment]
One of the things things that has caused me to miss issues in the past is the number of settings this plugin is accumulating. So I started writing up some baseline settings that we expect for tests. The idea being that we would then call out if specific settings need changing for certain tests.

So the start of our test script (or the initial setup for our automated tests) might look a bit like this:

#### WooCommerce Configuration
Setup a shipping zone so that we can test delivery addresses

#### Amazon Pay Plugin Settings
A fresh installation will more or less default to these, but it’s worth checking:

| **Amazon account details** |  |
| ------------- | ------------- |
| Use Login with Amazon App | On (might be hidden and forced on) |
| Subscriptions support | Yes
| **Advanced configurations** |  |
| Login Authorization Mode | Optimal
| Payment Capture | Authorize and Capture the payment when the order is placed
| Authorization processing mode | Optimal (fallback asynchronous attempt after synchronous failure)
| **Display options** |  |
| Cart login button display | Button
| Button type | Button with text Amazon Pay
| Button size | Medium
| Button color | Gold
| Button language | Detect from buyer’s browser
| Standard checkout button | Off
| **Miscellaneous** | |
| Debug | On
| Hide Button Mode | Off

**Comment by dwainm** [comment]
Another area we're not quite as prescriptive as I would like is stating test results. So, an example test scenario might be:

#### Successful Payment
Test Steps:

* Pick any delivery address
* Make a payment with the 1111 Visa card

Expected Results:

* Order received page shown to customer
* Order has status of “Processing”
* Billing and Shipping addresses match what the customer entered
* The Amazon Pay box on the right of the order screen shows “Completed”

Note that we enumerate out what we should expect to see for a "successful payment".

Then in terms of specific test scenarios, the list I've been using for reference includes:

* Purchase a product
   * Purchase a virtual product (no shipping)
   * MFA cards vs non-MFA cards
   * Card payment failure tests (specifically calling out TransactionTimedOut since this is handled differently)
* Purchase a subscription
   * Renewal correctly processed and charged
   * Purchase a subscription with a sign-up fee
   * Purchase a subscription with a free trial
* Test paying for a manually created order
* Perform tests in different regions / address formats
* Test with and without trial periods
* Test with and without signup fees
* Test with and without being logged into WordPress first
* Test on mobile (especially the login part because this is different on mobile)

**Comment by allendav** [comment]
Copied settings to https://github.com/woocommerce/woocommerce-gateway-amazon-pay/wiki/Basic-Extension-Settings
Copied tests to https://github.com/woocommerce/woocommerce-gateway-amazon-pay/wiki/Recommended-Manual-Testing
