### ISSUE TITLE
Amazon Pay wallet fails to fill in the province field

### ISSUE THREAD

**Issue by johndcoy** [woocommerce/woocommerce-gateway-amazon-pay#49]
**Describe the bug**
Amazon Pay's wallet fails to fill in the province field and billing details.

**To Reproduce**
1. Add a test account with an address in seller central, using a province in Spain. 

Example:
```
Address: Autovía de Levante, KM 34
City: Petrer
Province: Alicante
Country: Spain
Postal Code: 03610
```

2. Create a shipping zone specific to that province ( https://d.pr/i/jgqywF )
3. Use seller central test account on the checkout page to see other zone qualified ( https://d.pr/i/OB5Qf9 )

**Screenshots**
Screenshots to help explain the problem: https://d.pr/v/Zoc05O

**Expected behavior**
For the province field to be updated based on contents of address in Amazon Pay wallet.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only the extension is active.
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jrodger** [comment]
I haven't debugged this to confirm, but it feels like it could be a similar problem to https://github.com/woocommerce/woocommerce-gateway-amazon-pay/issues/34.

Set the priority the same as that issue for now, but we should consider increasing the priority of both if it's confirmed to be the same issue.

**Comment by treibalen** [comment]
Bumping it to High since this bug breaks checkout for affected users
