### ISSUE TITLE
Provide a way to suppress Amazon Pay on a specific page

### ISSUE THREAD

**Issue by prayagr** [woocommerce/woocommerce-gateway-amazon-pay#77]
**Describe the bug**
We're looking for a code sample that helps us turn off/block Amazon Pay on a specific page on the basis of the page Id or page title. We did not find a way to do it from the settings in the Amazon Pay plugin.

For context, a merchant has an internal page for employees only, but when an Amazon Pay button is rendered on this page, it breaks the custom checkout flow on this page. Hence, we would like to turn off the button rendering on this page.

Could you provide guidance or code samples that can help with this?

**To Reproduce**
None, this is a query.

**Screenshots**
NA

**Expected behavior**
Suppress Amazon Pay button from rendering on a specific page

**Isolating the problem (mark completed items with an [x]):**
NA

**WordPress Environment**
NA

**Comment by prayagr** [comment]
Hello, can I have someone take a look at this request?

**Comment by lauramelos** [comment]
hi @prayagr, the best way to remove amazon pay button is to remove the actions where the button is rendered, for example adding this code to your theme functions.php file:

`add_action( 'wp_head', 'remove_amazon_button_action' );
function remove_amazon_button_action() {
    remove_action( 'woocommerce_proceed_to_checkout', array( wc_apa(), 'checkout_button' ), 25 );
    remove_action( 'woocommerce_before_checkout_form', array( wc_apa(), 'checkout_message' ), 5 );
}
`
Those two removes the default buttons from cart and checkout, you can remove them conditionally  if  you need to. 

Please, let me know if this helps

**Comment by prayagr** [comment]
Thanks @lauramelos, this is very helpful. I'll get back to you once we verify this.

**Comment by alexiglesias31** [comment]
Closing this issue as there has been no recent news. Feel free to reopen if there are further updates or discussions.
