### ISSUE TITLE
Compatibility with "Pfand (Deposit) for WooCommerce Products"

### ISSUE THREAD

**Issue by ChristianAF** [woocommerce/woocommerce-gateway-amazon-pay#82]
**Describe the bug**
The Deposit price created by the plugin "Pfand (Deposit) for WooCommerce Products" is not been charge by Amazon Pay (Ver. 1.13.0 )

Related Woo TT: [ #3755714](https://woothemes.zendesk.com/agent/tickets/3755714)

**Comment by alexiglesias31** [comment]
Closing this issue as there has been no recent news. Feel free to reopen if there are further updates or discussions.
