### ISSUE TITLE
The discount of a product is been lost when using the plugin "Tiered Price Table for WooCommerce"

### ISSUE THREAD

**Issue by ChristianAF** [woocommerce/woocommerce-gateway-amazon-pay#87]
**Describe the bug**
When using the plugin "Tiered Price Table for WooCommerce" for discounts, the discount is been lost After placing the order. Amazon pay Charges the order total without the discount.

**To Reproduce**
1. install "Tiered Price Table for WooCommerce" and set up a product with a discount when buying 2 or more.
2. Add the product with the discount to Cart (Qty = 2 or depends on how is the descount setted)
3. got to checkout, log in to an Amazon account and place order (befor placing order check the order total)
4. On thankyou page the order total is without the discount

**Expected behavior**
Amazon pay should capture the order total with the discount

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only the extension is active.
- [X] I can reproduce this bug consistently using the steps above.

WooCommerce Ticket for details: https://woothemes.zendesk.com/agent/tickets/3730943
Saucal Ticket for details: https://saucal.zendesk.com/agent/tickets/7458

**Comment by alexiglesias31** [comment]
Closing this issue as there has been no recent news. Feel free to reopen if there are further updates or discussions.
