### ISSUE TITLE
Amazon Pay: cross site script invoked via document.write in Google Chrome

### ISSUE THREAD

**Issue by dwainm** [woocommerce/woocommerce-gateway-amazon-pay#9]
#### Affected ticket(s)

2104385-zen

#### What I expected

When opening a page that has the Amazon Pay button on it there are no errors in the browser console.

#### What happened instead

When a page with the Amazon Pay button is opened, a message appears in the console **warning** that a `parser-blocking, cross site [...] script, [...], is invoked via document.write.`, and that this may be blocked now or in the future.

The warning message in full:
>A parser-blocking, cross site (i.e. different eTLD+1) script, https://static-eu.payments-amazon.com/v2/login.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.

An image of the message as it appears in the Google Chrome console:

![https://cld.wthms.co/Dbmm7I](https://cld.wthms.co/Dbmm7I+)
Direct link to image: https://cld.wthms.co/Dbmm7I

#### Steps to reproduce the issue

**DISCLAIMER: I don't have a proper testing site set up yet, so the steps might not be accurate. I'd suggest having someone attempt to reproduce this in a more concrete way.**

1. Install the Amazon Pay extension.
2. Configure the extension.
3. Add Amazon Pay as a payment method during checkout.
4. Warning message appears on the checkout page, or wherever the Amazon Pay button is located.

#### Additional information

This issue is similar to #186, but seems to refer to a different script.

Mozilla Firefox doesn't seem to complain about the same script, but does block some Cross-Origin requests for Amazon, although these may be specific configuration issues with the customer in question from 2104385-zen, but seems worth looking into at the same time.

The 3 warnings are:

>Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://payments.amazon.de/checkout/clear?coe=DE&env=LIVE. (Reason: CORS request did not succeed).

>The resource at “https://payments.amazon.de/checkout/clear?coe=DE&env=LIVE” was blocked because content blocking is enabled.

>The resource at “https://payments.amazon.de/gp/apa/csm/jsonp?sellerId=undefined&data=%7B%27counters%27%3A%5B%5D%2C%27timings%27%3A%5B%7B%27name%27%3A%27walletwidget-pre-render%27%2C%27time%27%3A46%2C%27tags%27%3A%5B%5D%7D%5D%2C%27info%27%3A%5B%5D%2C%27entries%27%3A%5B%5D%7D” was blocked because content blocking is enabled.

Screenshot:

![https://cld.wthms.co/1vXi2N](https://cld.wthms.co/1vXi2N+)
Direct link to image: https://cld.wthms.co/1vXi2N 

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by alexiglesias31** [comment]
Closing the ticket since the issue is not reproducible anymore.
